# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.

# -- Path setup --------------------------------------------------------------

import os
import sys
import sphinx_rtd_theme

# -- Project information -----------------------------------------------------

project = 'Thermobar'
copyright = '2021, Penny Wieser'
author = 'Penny Wieser'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = 'v.0'

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here.
sys.path.insert(0, os.path.abspath('..'))

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx_rtd_theme",
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.intersphinx',
    'sphinx.ext.napoleon',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'IPython.sphinxext.ipython_directive',
    'IPython.sphinxext.ipython_console_highlighting',
    'nbsphinx',
    'sphinx.ext.viewcode',
    'sphinxcontrib.bibtex',
]

bibtex_bibfiles = ['references.bib']
bibtex_reference_style = 'author_year'

# --- RTD / GitHub context for nbsphinx links --------------------------------

on_rtd = os.environ.get('READTHEDOCS', '') == 'True'

# Use the actual ref RTD is building (branch/tag/commit),
# fall back to 'main' when building locally.
github_ref = os.environ.get('READTHEDOCS_GIT_IDENTIFIER', 'main') if on_rtd else 'main'

html_context = {
    'READTHEDOCS': on_rtd,
    'github_version': github_ref,
}

# --- nbsphinx prolog (adds the banner + buttons) ----------------------------

nbsphinx_prolog = r"""
{% set docname = 'docs/' + env.doc2path(env.docname, base=None) %}
{% set git_ref = env.config.html_context.get('github_version', 'main') %}

.. raw:: html

    <div class="admonition note">
      <p>
        This page was generated from
        <a class="reference external"
           href="https://github.com/PennyWieser/Thermobar/blob/{{ git_ref|e }}/{{ docname|e }}">
           {{ docname|e }}
        </a>.
      </p>
      <p>
        Interactive online version:
        <a class="reference external"
           href="https://mybinder.org/v2/gh/PennyWieser/Thermobar/{{ git_ref|e }}?filepath={{ docname|e }}">
           <img alt="Binder badge"
                src="https://mybinder.org/badge_logo.svg"
                style="vertical-align:text-bottom">
        </a>
      </p>
      <p>
        <a class="reference download internal" download=""
           href="https://github.com/PennyWieser/Thermobar/raw/{{ git_ref|e }}/{{ docname|e }}">
          <code class="xref download docutils literal notranslate">
            <span class="pre">Python</span>
            <span class="pre">Notebook</span>
            <span class="pre">Download</span>
          </code>
        </a>
      </p>
      <script>
        if (document.location.host) {
          var p = document.currentScript.previousSibling.previousSibling;
          var a = document.createElement('a');
          a.innerHTML = 'View in <em>nbviewer</em>';
          a.href = 'https://nbviewer.jupyter.org/url' +
                   (window.location.protocol === 'https:' ? 's/' : '/') +
                   window.location.host +
                   window.location.pathname.slice(0, -5) + 'ipynb';
          a.classList.add('reference');
          a.classList.add('external');
          p.appendChild(a);
          p.appendChild(document.createTextNode('.'));
        }
      </script>
    </div>

.. raw:: latex

    \nbsphinxstartnotebook{\scriptsize\noindent\strut
    \textcolor{gray}{The following section was generated from
    \sphinxcode{\sphinxupquote{\strut {{ docname | escape_latex }}}} \dotfill}}
"""

# -- Templates ----------------------------------------------------------------

templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx.
language = 'en'

# List of patterns, relative to source directory, to ignore.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output -------------------------------------------------

html_theme = "sphinx_rtd_theme"
# html_static_path = ['_static']  # (left commented as in your original)

# -- Options for HTMLHelp output ---------------------------------------------

htmlhelp_basename = 'Thermobardoc'

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # Keep your defaults
}

latex_documents = [
    (master_doc, 'Thermobar.tex', 'Thermobar Documentation',
     'Penny Wieser', 'manual'),
]

# -- Options for manual page output ------------------------------------------

man_pages = [
    (master_doc, 'Thermobar', 'Thermobar Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

texinfo_documents = [
    (master_doc, 'Thermobar', 'Thermobar Documentation',
     author, 'Thermobar', 'One line description of project.',
     'Miscellaneous'),
]

# -- Intersphinx -------------------------------------------------------------

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'pandas': ('https://pandas.pydata.org/en/latest', None),
    'numpy': ('https://docs.scipy.org/doc/numpy', None),
}
